### ISSUE TITLE
Setting TWISTED_REACTOR in Linux

### ISSUE THREAD

**Issue by JSPromisel** [scrapy-plugins/scrapy-zyte-api#8]
We are writing a spider that uses this plugin and need to have the `TWISTED_REACTOR` setting value be `twisted.internet.asyncioreactor.AsyncioSelectorReactor`. Once we upgraded to Scrapy 2.6.0, setting this via the spider's custom_settings worked when running in local dev environment `macOS Big Sur version 11.6`. However, in our production Linux environment, using the same code, we get an error:
```
Traceback (most recent call last):
  File "sayari/production_runner.py", line 88, in <module>
    crawl(sys.argv[-1])
  File "sayari/production_runner.py", line 76, in crawl
    runner.crawl(spider)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 205, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 238, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 243, in _create_crawler
    return Crawler(spidercls, self.settings)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 85, in __init__
    verify_installed_reactor(reactor_class)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/utils/reactor.py", line 90, in verify_installed_reactor
    raise Exception(msg)
Exception: The installed reactor (twisted.internet.epollreactor.EPollReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)
```
The Linux environment is:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Is this difference in behavior expected? Are there any suggested fixes? We'd like to use this plugin for our use of the API but using the `twisted.internet.asyncioreactor.AsyncioSelectorReactor` has proven difficult.

For reference, this is how we are running the spiders:
```
from scrapy import spiderloader
from scrapy.crawler import CrawlerRunner
from scrapy.utils.project import get_project_settings
from twisted.internet import reactor

def crawl(spider_name):
    # Load project settings
    project_settings = get_project_settings()

    # Load spider
    spider_loader = spiderloader.SpiderLoader.from_settings(project_settings)
    spider = spider_loader.load(spider_name)

    # Create the crawler runner
    runner = CrawlerRunner(project_settings)
    runner.crawl(spider)
    d = runner.join()
    d.addBoth(lambda _: reactor.stop())

    # Run the twisted reactor
    reactor.run()
```

**Comment by BurnzZ** [comment]
Hi @JSPromisel , may I ask if you tried running `scrapy.utils.reactor.install_reactor()` before running the crawl process? Reference: https://docs.scrapy.org/en/latest/topics/settings.html#scrapy.utils.reactor.install_reactor
